development:
  adapter: postgresql
  encoding: unicode
  database: choongang_development
  pool: 5
  username: choongang
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: choongang_test
  pool: 5
  username: choongang
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: choongang_production
  pool: 5
  username: choongang
  password:
